from . import hospital_service
from . import hospital_directory_diseases
from . import hospital_research_type
from . import hospital_sample_type
from . import hospital_doctor_schedule
from . import hospital_doctor_visit
from . import hospital_research
from . import hospital_diagnosis
from . import hospital_personal_doctor_history
from . import hospital_change_doctor_wizard
from . import hospital_abstract_person
from . import hospital_contact_person
from . import hospital_doctor
from . import hospital_patient
from . import hospital_report_wizard
